/** Engine credentials files, written by the create_client tool. See README.md. */
import { execFile } from "node:child_process";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { basename, dirname, isAbsolute, resolve } from "node:path";
import { promisify } from "node:util";
import type { CoreAdminClient } from "./coreadmin.js";
import { CLIENT_NAME_MAX_LENGTH } from "./coreadmin.js";
import { RpsError, parseEnvFile, type EngineCredentials, type RpsConfig } from "./rps.js";

const execFileAsync = promisify(execFile);

export const DEFAULT_CLIENT_NAME = "kustodyan-mcp";

/** First line of every file this MCP writes; anything else is not ours to replace. */
const GENERATED_HEADER = "# Generated by kustodyan-mcp";

export function clientNameFromEnv(env = process.env): string {
  const name = env.KUSTODYAN_CLIENT_NAME || DEFAULT_CLIENT_NAME;
  if (name.length > CLIENT_NAME_MAX_LENGTH) {
    throw new Error(`KUSTODYAN_CLIENT_NAME is longer than ${CLIENT_NAME_MAX_LENGTH} characters`);
  }
  return name;
}

/** The server's working directory belongs to the MCP client, not to the project. */
export function absoluteCredentialsPath(path: string): string {
  if (!isAbsolute(path)) {
    throw new RpsError(`credentials_file must be an absolute path, got "${path}"`);
  }
  return resolve(path);
}

export async function readCredentialsFile(path: string): Promise<EngineCredentials> {
  const filePath = absoluteCredentialsPath(path);
  let text: string;
  try {
    text = await readFile(filePath, "utf8");
  } catch {
    throw new RpsError(`Cannot read Engine credentials at ${filePath}: run create_client first`);
  }
  const { KUSTODYAN_CLIENT_ID: clientId, KUSTODYAN_CLIENT_SECRET: clientSecret } = parseEnvFile(text);
  if (!clientId || !clientSecret) {
    throw new RpsError(
      `${filePath} has no KUSTODYAN_CLIENT_ID / KUSTODYAN_CLIENT_SECRET: ` +
      "run create_client to (re)generate it");
  }
  return { clientId, clientSecret };
}

export async function createClient(
  coreAdmin: CoreAdminClient,
  clientName: string,
  rps: RpsConfig,
  path: string,
): Promise<{ clientId: string; created: boolean; credentialsFile: string }> {
  const filePath = absoluteCredentialsPath(path);
  // Validate the destination before touching CoreAdmin: ensureClient rotates
  // the secret and the new one is never returned, so a refused write after
  // rotation would strand the client with no usable credentials anywhere.
  await assertWritableDestination(filePath);
  const { clientId, clientSecret, created } = await coreAdmin.ensureClient(clientName);
  await writeCredentialsFile(filePath, clientName, rps, { clientId, clientSecret });
  return { clientId, created, credentialsFile: filePath };
}

async function assertWritableDestination(filePath: string): Promise<void> {
  // Create the directory before the guards: git check-ignore cannot run from
  // a missing directory, and its spawn failure would look like "no git".
  await mkdir(dirname(filePath), { recursive: true, mode: 0o700 });
  await assertOursOrAbsent(filePath);
  await assertGitIgnored(filePath);
}

async function writeCredentialsFile(
  filePath: string,
  clientName: string,
  rps: RpsConfig,
  creds: EngineCredentials,
): Promise<void> {
  // Guards re-run so the write is safe on its own; the pre-rotation check in
  // createClient exists only to fail before the secret is regenerated.
  await assertWritableDestination(filePath);
  const body = [
    `${GENERATED_HEADER} for the API client "${clientName}".`,
    "# Do not edit or commit. Recreate it with the create_client tool.",
    `KUSTODYAN_IDENTITY_URL=${rps.identityUrl}`,
    `KUSTODYAN_ENGINE_URL=${rps.engineUrl}`,
    `KUSTODYAN_CLIENT_ID=${creds.clientId}`,
    `KUSTODYAN_CLIENT_SECRET=${creds.clientSecret}`,
    "",
  ].join("\n");
  // Write then rename, so the secret is 0600 from the moment it exists on disk.
  const tmp = `${filePath}.${process.pid}.tmp`;
  await writeFile(tmp, body, { mode: 0o600 });
  await rename(tmp, filePath);
}

/** The write is a full rewrite, so it must not land on someone else's file. */
async function assertOursOrAbsent(filePath: string): Promise<void> {
  let text: string;
  try {
    text = await readFile(filePath, "utf8");
  } catch {
    return; // nothing there yet
  }
  if (!text.startsWith(GENERATED_HEADER)) {
    throw new RpsError(
      `Refusing to overwrite ${filePath}: it was not generated by kustodyan-mcp. ` +
      "Point create_client at a dedicated file.");
  }
}

/** Paths outside a repository, and machines without git, are left alone. */
async function assertGitIgnored(filePath: string): Promise<void> {
  try {
    await execFileAsync("git", ["check-ignore", "-q", "--", filePath], { cwd: dirname(filePath) });
  } catch (e) {
    if ((e as { code?: number | string }).code !== 1) return;
    throw new RpsError(
      `Refusing to write Engine credentials to ${filePath}: git does not ignore it. ` +
      `Add "${basename(filePath)}" to .gitignore, or point create_client at an ignored path.`);
  }
}
